### ISSUE TITLE
Receive Transaction Response

### ISSUE THREAD

**Issue by Abhisek-17** [PhonePe/phonepe-pg-sdk-flutter#1]
Can we get more detailed transaction info after payment? The current true/false response isn't enough. If possible, please let me know how to get this info. While using Flutter SDK

**Comment by J-Nokwal** [comment]
Hii @Abhisek-17
were you able to do transactions from UPI intent?

**Comment by Abhisek-17** [comment]
Haven't tried UPI Intent yet, but PAY_PAGE works for transactions.

**Comment by premiereessential** [comment]
hi, I want to accept payment with UPI Intent. I have some doubt about body and checksum.
can you help with that and there is any video tutorial for this

**Comment by Rohit19060** [comment]
Got this error ({error: Transaction Interrupted!, status: FAILURE}) on startPGTransaction

**Comment by rajanarora27** [comment]
Please refer to https://developer.phonepe.com/v1/docs/flutter-sdk-integration for instructions on generating the body and checksum. For any questions, contact us at merchant-pgsupport@phonepe.com.
