### ISSUE TITLE
key_error_result:{"success":false,"code":"INTERNAL_SERVER_ERROR","message":"There is an error trying to process your transaction at the moment. Please try again in a while. [message = Error in application validation]","data":{}}

### ISSUE THREAD

**Issue by hitanshu1** [PhonePe/phonepe-pg-sdk-flutter#10]
My code is bellow .. same code working in iphone but when run in android phone sdk not open with error 
key_error_result:{"success":false,"code":"INTERNAL_SERVER_ERROR","message":"There is an error trying to process your transaction at the moment. Please try again in a while. [message = Error in application validation]","data":{}}

 final data = {
      "merchantId": merchantId,
      "merchantTransactionId": _merchantTransactionId,
      "merchantUserId": merchantUserId,
      "amount": '${amount*100}',
      "redirectUrl": "https://webhook.site/redirect-url",
      "redirectMode": "REDIRECT",
      "callbackUrl": "https://webhook.site/callback-url",
      "mobileNumber": "9123456789",
      "paymentInstrument": {
        "type": "PAY_PAGE"
      }
    };
 final b64 = jsonEncode(data).toBase64;

    print(b64);

   
    String apiEndPoint = "/pg/v1/pay";
    final sha = '$b64$apiEndPoint$saltKey'.toSha256;
    String callback = "flutterDemoApp";
    Map<String, String> pgHeaders = {"Content-Type": "application/json",};
    print(sha);
    final saltIndex='1';

    String checksum = '$sha###$saltIndex';

    print('b64===$b64');
    print('checksum===$checksum');
    try {
      final response= await PhonePePaymentSdk.startPGTransaction(
          b64, callback, checksum, pgHeaders, apiEndPoint, packageName);

      if (response != null) {
        print('response===$response');
        String status = response['status'].toString();
        String error = response['error'].toString();
        if (status == 'SUCCESS') {
          result = "Flow Completed - Status: Success!";
          String _randomOrderID=RandomNumberString.getRandomString(10);
          await _orderCheckOut('success', 'COD', _randomOrderID, 'phonepe');
          hideLoader();

        } else {
          hideLoader();
          result =
          "Flow Completed - Status: $status and Error: $error";
          showToast(error);

        }
      } else {
        result = "Flow Incomplete";
        hideLoader();
      }

      print(result);
    } catch (error) {
      isLoading=false;
      setState(() { });

      handleError(error);
    }

**Comment by vysakhrj** [comment]
Same issue here. Have you found any workaround?

**Comment by vysakhrj** [comment]
Check whether you are using the uat mechantId and details itself. Avoid mixing test credentials and body

**Comment by NitinVermaPpe** [comment]
please react out on [merchant-integration@phonepe.com](mailto:merchant-integration@phonepe.com).

also please update to latest plugin version. app id is no longer mandatory
