### ISSUE TITLE
The operation couldn’t be completed

### ISSUE THREAD

**Issue by akkuashkar** [PhonePe/phonepe-pg-sdk-flutter#13]
PhonePePayment[debug]: Event name: B2B_PG_API_CALL_FAILED - data: ["message": "The operation couldn’t be completed. (PhonePePayment.HTTPClientError error 0.)"]

**Comment by NitinVermaPpe** [comment]
please react out on [merchant-integration@phonepe.com](mailto:merchant-integration@phonepe.com)
