### ISSUE TITLE
Any one help me how can get app ID in production 

### ISSUE THREAD

**Issue by naseefvaliyakath** [PhonePe/phonepe-pg-sdk-flutter#14]
Pleas help me to how generate or how get App ID for android and IOS if its in production

**Comment by ragsanil** [comment]
You need to get package signature for your application in production by using phonepesdk, then share this with phonepe team and they will generate and give you appId.

**Comment by naseefvaliyakath** [comment]
That same signature is enough for if i publish in playstore?

**Comment by NitinVermaPpe** [comment]
app id is no longer mandatory on newer versions of sdk
please react out on [merchant-integration@phonepe.com](mailto:merchant-integration@phonepe.com)
