### ISSUE TITLE
getting 401 error response

### ISSUE THREAD

**Issue by iresolveservices** [PhonePe/phonepe-pg-sdk-flutter#15]
after pass all valid inputs it throws 401 error 

body eyJtZXJjaGFudElkIjoiTUVSQ0hBTlRVQVQiLCJtZXJjaGFudFRyYW5zYWN0aW9uSWQiOiJNVDc4NTA1OTAwNjgxODgxMDQiLCJtZXJjaGFudFVzZXJJZCI6Ik1VSUQxMjMiLCJhbW91bnQiOjEwMDAwLCJjYWxsYmFja1VybCI6Imh0dHBzOi8vd2ViaG9vay5zaXRlL2NhbGxiYWNrLXVybCIsIm1vYmlsZU51bWJlciI6Ijk5OTk5OTk5OTkiLCJwYXltZW50SW5zdHJ1bWVudCI6eyJ0eXBlIjoiUEFZX1BBR0UifX0=
I/flutter (29187): callback ***********************************
I/flutter (29187): checksum 95f463108ed415b2d186b37cde32da19d6db009afc7cb15e06f08b40db5e7074###1
I/flutter (29187): packageName com.phonepe.simulator
I/flutter (29187): response aa {error: key_error_code:ERROR_B2B_API_RETURNED_ERROR
I/flutter (29187): key_error_result:{"code":"401","success":false}
I/flutter (29187): , status: FAILURE}

 key_error_result:{"code":"401","success":false}
 
 
 ref Code
 
 
  void startTransaction() async {
    try {
      PhonePePaymentSdk.startTransaction(body, callback, checksum, packageName)
          .then((response) => {
        setState(() {

          if (response != null) {
            print('body  $body');
            print('callback  $callback');
            print('checksum  $checksum');
            print('packageName  $packageName');
            print('response  $response');
            String status = response['status'].toString();
            String error = response['error'].toString();
            if (status == 'SUCCESS') {
              result = "Flow Completed - Status: Success!";
            } else {
              result =
              "Flow Completed - Status: $status and Error: $error";
            }
          } else {
            result = "Flow Incomplete";
          }
        })
      })
          .catchError((error) {
        handleError(error);
        return <dynamic>{};
      });
    } catch (error) {
      handleError(error);
    }
  }

**Comment by NitinVermaPpe** [comment]
please react out on [merchant-integration@phonepe.com](mailto:merchant-integration@phonepe.com)
