### ISSUE TITLE
How to integrate with Backend Server?

### ISSUE THREAD

**Issue by aradhya2211** [PhonePe/phonepe-pg-sdk-flutter#16]
There's no clarity on the flow of the payments using SDK. Currently we have integrated phonePe, using the following flow:

Flutter Client -> our backend -> pp backend (PAY API) -> return payment url -> redirect client to payment url -> wait for webhook/recon process -> check status API -> show result to user

But with SDK what will be the flow to securely integrate with our backend server? 

If there's any link to this flow or documentation pls share. As I didn't find anything on phone pe docs..

**Comment by NitinVermaPpe** [comment]
hey you can reach out to [merchant-integration@phonepe.com](mailto:merchant-integration@phonepe.com) to understand the flow.

but I do agree with your concern. For now, I have made below diagram. 
Let me know if you have any feedback on this. we will soon publish it on our dev docs

<img width="962" alt="Screenshot 2024-04-12 at 4 51 36 PM" src="https://github.com/PhonePe/phonepe-pg-sdk-flutter/assets/165249115/6e17c6ef-4fe9-4968-9c47-625b3792ad40">

**Comment by aradhya2211** [comment]
Thanks for sharing the flow, is it safe to send base64/encoded data back to the client? I highly recommend you not to discontinue the Pay API.. instead return a masked token which can be passed to the SDK!

**Comment by aradhya2211** [comment]
Okay thanks.. the flow will be the same for flutter web right?

**Comment by NitinVermaPpe** [comment]
wherever you are using sdk, above shared flow will work. https://github.com/PhonePe/phonepe-pg-sdk-flutter/issues/16#issuecomment-2051571007

for sdk-less integration, you have already mentioned the flow in the issue. https://github.com/PhonePe/phonepe-pg-sdk-flutter/issues/16#issue-2238962979
