### ISSUE TITLE
key_error_code: ERROR_B2B_API_RETURNED_ERROR status: FAILURE | key_error_result:{"success":false,"code":"TOO_MANY_REQUESTS", "message": "Too many requests. Please try again.","data":{}}

### ISSUE THREAD

**Issue by Sahilkathir** [PhonePe/phonepe-pg-sdk-flutter#18]
i have get this error

key_error_code: ERROR_B2B_API_RETURNED_ERROR status: FAILURE | key_error_result:{"success":false,"code":"TOO_MANY_REQUESTS", "message": "Too many requests. Please try again.","data":{}}

Why am I getting this error again and again . I am using testing mode MerchantId and API keys. Please help

**Comment by NitinVermaPpe** [comment]
hi, please reach out to [merchant-integration@phonepe.com](mailto:merchant-integration@phonepe.com)
