### ISSUE TITLE
dedicated tutorial for UPI Intent

### ISSUE THREAD

**Issue by premiereessential** [PhonePe/phonepe-pg-sdk-flutter#3]
hi, I want to accept payment with UPI Intent. I have some doubt about body and checksum.
can you help with that and there is any video tutorial for this

**Comment by rajanarora27** [comment]
As of now, We have the documentation for the integration. 

Please check: https://developer.phonepe.com/v1/docs/flutter-sdk-integration

We will add a video in future for this.
