### ISSUE TITLE
"I can't implement it; I need a good video presentation or clear developer documentation."

### ISSUE THREAD

**Issue by basheerbsr79** [PhonePe/phonepe-pg-sdk-flutter#4]
"I can't make the payment from my Flutter app. What is the callback URL, and can I add any code on the server side or website to implement it? Has anyone successfully used this SDK to make payments and receive the status?"

**Comment by premiereessential** [comment]
I am also looking for this

**Comment by HeyAvi** [comment]
Hello, I'm also looking for a clear guide for the implementation @rajanarora27  as I cannot guess what is app id, what is the checksum. In Razorpay it is straightforward, please write proper documentation or upload a YouTube video. As I can see the method written in the documentation is Jugaad, it's not a proper method.

**Comment by rajanarora27** [comment]
Hi @all, Please refer to this doc for step-by-step implementation : 
https://developer.phonepe.com/v1/docs/flutter-sdk-integration
