### ISSUE TITLE
Error Occur in Production

### ISSUE THREAD

**Issue by premiereessential** [PhonePe/phonepe-pg-sdk-flutter#7]
If you need any help regarding PhonePe Integration, reach out to us

**Comment by sahil6104g** [comment]
Hello @premiereessential ,

I am facing same issue when I select Production Mode. It shows error "Transaction Interrupted". 

Could you please help me?

**Comment by priyanshgmits** [comment]
I am encountering the same issue in production mode as reported previously. I kindly request assistance in resolving this issue to ensure the smooth operation of our production environment.
![Screenshot_20231027_123739](https://github.com/PhonePe/phonepe-pg-sdk-flutter/assets/149144511/306d5cf6-8a29-436a-99d0-c294602a77d2)

**Comment by skpatel9081** [comment]
I am facing this issue in Production Mode. It throw an error "Transaction are  Interrupted".

Please resolve this issuse as soon as possible..

Can you help me??

**Comment by premiereessential** [comment]
Salt key is not whitelisted by PhonePe team.
Talk to them and get approve your credentials for production

**Comment by sahil6104g** [comment]
@premiereessential Thanks for your support. I will contact PhonePe Team.

**Comment by mustansirgodhrawala** [comment]
https://www.mustansirg.in/post/phonepe-payment-gateway-flutter

**Comment by priyanshgmits** [comment]
Hello @mustansirgodhrawala ,
Is package signature different for debug and release app? as they will provide app id once we provider package signature to phonepe team.

**Comment by mustansirgodhrawala** [comment]
Yeah, so based on what your signing method is it will definitely be different. You can reach out to me on LinkedIn at linkedin.com/in/mustansirg and I can help you out more.

You might want to upload it to internal testing to get the package signature to send to PhonePe, it is the safest way to get it.

**Comment by NitinVermaPpe** [comment]
please react out on [merchant-integration@phonepe.com](mailto:merchant-integration@phonepe.com)

also update to latest plugin version, app id/ signing key is no longer mandatory
