### ISSUE TITLE
The PhonePe docs are not clear enough and the package is too complex for newbies to understand

### ISSUE THREAD

**Issue by mustansirgodhrawala** [PhonePe/phonepe-pg-sdk-flutter#9]
Read about my implementation as a fullstack engineer at my blog 
https://www.mustansirg.in/post/phonepe-payment-gateway-flutter

**Comment by premiereessential** [comment]
hi, I am getting error, can you help me 
![WhatsApp Image 2023-11-11 at 3 13 45 PM](https://github.com/PhonePe/phonepe-pg-sdk-flutter/assets/103051469/ccba1418-127c-44c4-9de4-c991da546d1b)
